# Generated by Django 4.2.11 on 2026-09-03 08:31

from django.db import migrations, models
import django.db.models.deletion


def backfill_published_data(apps, schema_editor):
    Dialogue = apps.get_model('dialogues', 'Dialogue')
    DialogueLiterature = apps.get_model('dialogues', 'DialogueLiterature')
    Dialogue.objects.filter(status='published', published_at__isnull=True).update(
        published_at=models.F('created_at')
    )
    for dialogue in Dialogue.objects.exclude(recommended_literature=''):
        text = dialogue.recommended_literature.strip()
        if text:
            DialogueLiterature.objects.create(
                dialogue_id=dialogue.id,
                title=text[:500],
                annotation=text if len(text) > 500 else '',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dialogues', '0010_dialogueresourceproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialogueillustration',
            name='origin',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'Generated'), ('found', 'Found online')], default='uploaded', max_length=16),
        ),
        migrations.AddField(
            model_name='dialogueillustration',
            name='source_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dialogueillustration',
            name='source_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.CreateModel(
            name='DialogueLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(max_length=500)),
                ('annotation', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='literature_items', to='dialogues.dialogue')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(backfill_published_data, migrations.RunPython.noop),
    ]
